"""
Zero-config .ics calendar integration
- Generates RFC 5545 compliant .ics files
- Works offline with any calendar app (Google, Outlook, Apple)
- One-click "Add to Calendar" from UI
"""
from datetime import datetime, timedelta, timezone
import uuid
import streamlit as st

class CalendarEvent:
    def __init__(self, summary, description, start_datetime, duration_hours=1):
        self.summary = summary
        self.description = description
        self.start = start_datetime
        self.end = start_datetime + timedelta(hours=duration_hours)
        self.uid = f"{uuid.uuid4()}@jobtracker.local"
        self.created = datetime.now(timezone.utc)
    
    def to_ics(self):
        """Generate RFC 5545 compliant .ics content"""
        ics_template = f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//JobTrack Pro//Calendar//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:{self.uid}
DTSTAMP:{self.created.strftime('%Y%m%dT%H%M%SZ')}
DTSTART:{self.start.strftime('%Y%m%dT%H%M%SZ')}
DTEND:{self.end.strftime('%Y%m%dT%H%M%SZ')}
SUMMARY:{self.summary}
DESCRIPTION:{self.description}
STATUS:CONFIRMED
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR"""
        return ics_template.replace("\n", "\r\n")  # Windows line endings

def create_followup_event(contact_name, company_name, days_until=7):
    """Create follow-up reminder event"""
    start_time = datetime.now(timezone.utc) + timedelta(days=days_until)
    summary = f"Follow up: {contact_name} @ {company_name}"
    description = f"""Follow up with {contact_name} regarding job application.
    
Company: {company_name}
Contact: {contact_name}
    
Generated by JobTrack Pro - https://github.com/yourusername/jobtracker"""
    
    return CalendarEvent(summary, description, start_time)

def create_interview_event(job_title, company_name, interview_datetime):
    """Create interview reminder event"""
    summary = f"Interview: {job_title} @ {company_name}"
    description = f"""Interview for {job_title} position at {company_name}.
    
Good luck! 🚀
    
Generated by JobTrack Pro"""
    
    return CalendarEvent(summary, description, interview_datetime, duration_hours=2)

# Streamlit UI Component
def calendar_download_button(event, label="📥 Add to Calendar"):
    """One-click calendar download button"""
    ics_content = event.to_ics()
    st.download_button(
        label=label,
        data=ics_content,
        file_name=f"{event.summary.replace(' ', '_').lower()}.ics",
        mime="text/calendar",
        use_container_width=True
    )